### ISSUE TITLE
Move appdata file to upstream repository

### ISSUE THREAD

**Issue by barthalion** [flathub/com.valvesoftware.Steam.Utility.protontricks#1]
As mentioned in [initial review](https://github.com/flathub/flathub/pull/1259), the appdata file should be shipped upstream as it's useful for other distributions.

**Comment by Matoking** [comment]
It's upstream now:

https://github.com/Matoking/protontricks/blob/master/data/com.valvesoftware.Steam.Utility.protontricks.metainfo.xml

I'll update the build manifest next time a new Protontricks release is made to keep the build manifest tidy.
