### ISSUE TITLE
update sdk to 20.08

### ISSUE THREAD

**Issue by LeandroStanger** [flathub/com.valvesoftware.Steam.Utility.protontricks#14]

**Comment by ranisalt** [comment]
Even though flathub/com.valvesoftware.Steam#572 was closed and pointed here, I still can't run protontricks inside flatpak after updating it.

**Comment by ccat3z** [comment]
> Even though [flathub/com.valvesoftware.Steam#572](https://github.com/flathub/com.valvesoftware.Steam/issues/572) was closed and pointed here, I still can't run protontricks inside flatpak after updating it.

Here is a temporary workaround before https://github.com/flathub/com.valvesoftware.Steam/commit/798fb1a46b553cf5855fe9e31591e20d2bf9ed91 is merged into master. Try to override these environment variables of com.valvesoftware.Steam.

```
[Environment]
PATH=/app/utils/protontricks/bin:/app/bin:/usr/bin
LD_LIBRARY_PATH=/app/utils/protontricks/lib
PYTHONPATH=/app/utils/protontricks/lib/python3.8/site-packages
```

**Comment by Matoking** [comment]
Reopening the issue for visibility.

The Flatpak is updated to SDK 20.08, but like @ccat3z said there's still a different issue that needs to be solved in the Steam Flatpak side of things before Protontricks works again.

**Comment by Matoking** [comment]
Protontricks has worked again for a while, so closing this issue.

**Comment by YasirAnqa** [comment]
I'm having this issue. I have followed the instructions mentioned [here](https://github.com/flathub/com.valvesoftware.Steam.Utility.protontricks#installation) but it didn't seem to work. I get the following error message:
`bwrap: execvp protontricks: No such file or directory`
