### ISSUE TITLE
Missing cabextract

### ISSUE THREAD

**Issue by dariox86** [flathub/com.valvesoftware.Steam.Utility.protontricks#22]
When trying to install xact, winetricks complains about missing cabextract.

**Comment by Matoking** [comment]
I'm unable to reproduce this with the stable Steam Flatpak. Are you running a different version of the Steam Flatpak?

Also, please provide a copy of the output that appears when trying to run a command. You can post it to [gist.github.com](https://gist.github.com/) to prevent cluttering the thread.

**Comment by dariox86** [comment]
I was trying to install xact from GUI and since the progress bar needed Perl, cabextract failed because it was unable to extract a non-existent archive. It is working now. Thank you.
